### ISSUE TITLE
Program closes with KeyError if the Gradebook is not available in StudentVue

### ISSUE THREAD

**Issue by aarushtools** [JasonGrace2282/hacktj24#5]
### Outline of the bug
Program unexpectedly closes with KeyError "Gradebook" after logging in while the gradebook is unavailable (closed)

### How to encounter/reproduce bug
Login to a SIS domain while the gradebook is closed

### Expected behavior
The program displays a message on the gradebook being closed 

### Actual behavior
The program unexpectedly quits and displays a KeyError in the console and raises a runtime error in the console

**Log**
```Traceback (most recent call last):
  File "C:\Users\thisi\asSISt\loading.py", line 46, in <module>
    root.wm_attributes('-type', 'floating')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 2005, in wm_attributes
    return self.tk.call(args)
_tkinter.TclError: bad attribute "-type": must be -alpha, -transparentcolor, -disabled, -fullscreen, -toolwindow, or -topmost
Traceback (most recent call last):
  File "C:\Users\thisi\asSISt\backend\synergy.py", line 25, in check_account_success
    return StudentVue(
KeyError: 'Gradebook'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\thisi\asSISt\main.py", line 141, in <module>
    main()
  File "C:\Users\thisi\asSISt\main.py", line 137, in main
    App()
  File "C:\Users\thisi\asSISt\main.py", line 42, in __init__
    self.account = login(
  File "C:\Users\thisi\asSISt\backend\synergy.py", line 7, in login
    account = check_account_success(username, password, domain)
  File "C:\Users\thisi\asSISt\backend\synergy.py", line 31, in check_account_success
    raise RuntimeError("Oops, an error occurred with logging in") from e
RuntimeError: Oops, an error occurred with logging in```

**Comment by JasonGrace2282** [comment]
We are working on this, unfortunately time is a bit scarce. If you want to fix it, feel free to send a patch.
